on: push

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 30
    steps:
      - uses: hugheylab/actions/test-coverage@main
